"""WAF fingerprint + adaptive payload profile."""
from __future__ import annotations

import re
from typing import Dict, List, Optional

from utils.logger import get_logger

logger = get_logger(__name__)

_SIGNATURES = {
    "cloudflare": [r"cloudflare", r"cf-ray", r"__cfduid", r"attention required"],
    "akamai": [r"akamai", r"ak_bmsc", r"_abck"],
    "modsecurity": [r"mod_security", r"modsecurity", r"this error was generated by mod_security"],
    "aws_waf": [r"awselb", r"x-amzn-requestid", r"aws.?waf"],
    "imperva": [r"incapsula", r"imperva", r"visid_incap"],
    "sucuri": [r"sucuri", r"x-sucuri"],
    "f5_bigip": [r"bigip", r"f5", r"ts[0-9a-f]{8}"],
}


class WAFFingerprint:
    def __init__(self, http_client, config: Dict):
        self.http_client = http_client
        self.config = config

    def detect(self, url: str, response=None) -> Dict:
        headers = {}
        body = ""
        if response is None and self.http_client:
            response = self.http_client.get(url)
        if response is not None:
            headers = {k.lower(): str(v) for k, v in dict(getattr(response, "headers", {}) or {}).items()}
            body = (getattr(response, "text", None) or "")[:4000]
        blob = " ".join(headers.values()) + " " + body
        blob_l = blob.lower()
        hits = []
        for name, pats in _SIGNATURES.items():
            for p in pats:
                if re.search(p, blob_l, re.I):
                    hits.append(name)
                    break
        waf = hits[0] if hits else "none"
        profile = self.payload_profile(waf)
        return {"waf": waf, "all": hits, "payload_profile": profile}

    def payload_profile(self, waf: str) -> Dict:
        profiles = {
            "cloudflare": {
                "prefer_encoding": ["url", "unicode", "double_url"],
                "avoid": ["script_tag_raw"],
                "case_swap": True,
            },
            "modsecurity": {
                "prefer_encoding": ["comment_insert", "case_swap", "null_byte"],
                "avoid": [],
                "case_swap": True,
            },
            "akamai": {
                "prefer_encoding": ["base64", "hex", "url"],
                "avoid": [],
                "case_swap": False,
            },
            "none": {
                "prefer_encoding": ["plain"],
                "avoid": [],
                "case_swap": False,
            },
        }
        return profiles.get(waf, profiles["none"])

    def scan(self, url: str, context: Optional[Dict] = None) -> List[Dict]:
        ctx = context or {}
        info = self.detect(url, ctx.get("response"))
        if info["waf"] == "none":
            return []
        return [
            {
                "type": "WAF Detected",
                "severity": "info",
                "url": url,
                "parameter": "",
                "payload": "",
                "evidence": f"WAF fingerprint: {info['waf']} ({', '.join(info['all'])})",
                "description": f"Traffic appears filtered by {info['waf']}",
                "remediation": "Tune payloads / confirm authorized testing against WAF",
                "waf_profile": info["payload_profile"],
            }
        ]
